
GameTexts = {

  titleScreen = [=[
INMATARIAN'S
SMELLY HIPSTER
ARTSY JUMPER
GAME
 
PRESS ENTER TO PLAY
]=],

  gameOverScreen = [=[
LET'S END IT HERE.
GAME OVER
]=],

  instructionScreen = [=[
COLLECT ALL OBJECTS
 
ARROWS: MOVE, JUMP
R: RESTART LEVEL
F5: WINDOW SIZE
F10: QUIT
 
ENTER: ADVANCE TEXT
]=],

  levels = {
    "INSERT POSTMODERN, MASTURBATORY, SMARTPHONE-LOVING TEXT HERE.",
    "WOULD THIS BE BETTER IF IT WAS ANGRY OR EXISTENTIAL?",
    "COULD IT MAKE A COOL MILLION ON KICKSTARTER? I HAVE LAME IDEAS ALSO!",
    "HOW MANY LIKES IS THIS WORTH ON A SOCIAL NETWORK THAT I DON'T CARE ABOUT?",
    "WOULD ANYONE BUY IT FOR $2 IN THE CRAPP STORE?",
    "HOW LONG BEFORE THEY GET SICK OF RANDOMLY GENERATE LEVELS?",
    "WHEN DO THE COINS NO LONGER MAKE SENSE AS THE COLLECTABLE?",
    "MAYBE IF THE MUSICIAN WAS SOMEONE POPULAR.",
    "GAME OF THE YEAR AWARD FOR BEING BORN SOME PLACE INTERESTING.",
    "CONTROVERSIAL DESIGNER BECAUSE OF A HAIR PRODUCT.",
    "TWO YEARS OF HYPE MAKES THINGS INSTANTLY BETTER.",
    "BUILDING ON A FRANCHISE THAT WE WERE SICK OF AFTER THE FIRST DECADE.",
    "PRENTENDING TO BE STILL RELEVANT AFTER A CAREER THAT ENDED IN THE 90s.",
    "IT WOULD HAVE BETTER IF YOU STOOD UP AND WAGGLED YOUR ARMS AROUND.",
    "I'M GLAD TO GET ALL OF THAT OFF MY CHEST."
  };
}

